# Generated by Django 2.0.2 on 2018-08-21 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(default='money', max_length=70)),
                ('now_status', models.CharField(default='no money', max_length=2000)),
                ('future_status', models.CharField(default='a lot of money', max_length=2000)),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'ordering': ['-mtime', '-ctime'],
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(max_length=70)),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('time_choice', models.CharField(choices=[('long_time', '长期执行'), ('period_time', '阶段执行')], default='long_time', max_length=8, verbose_name='任务时间属性')),
                ('start_time', models.DateTimeField(verbose_name='开始日期')),
                ('end_time', models.DateTimeField(verbose_name='结束日期')),
                ('content', models.CharField(max_length=2000)),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process', to='plans.Plans')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_status', models.CharField(choices=[('complete', '完成'), ('do', '执行'), ('try', '尝试'), ('forget', '遗忘')], default='forget', max_length=8, verbose_name='任务时间属性')),
                ('process_score', models.IntegerField(default=0, verbose_name='分数')),
                ('process_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='plans.Process')),
            ],
        ),
    ]
