# Generated by Django 2.0.2 on 2018-08-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='time_choice',
            field=models.CharField(choices=[('long_time', '长期执行'), ('period_time', '阶段执行')], default='long_time', max_length=20, verbose_name='任务时间属性'),
        ),
    ]
