# Generated by Django 2.0.2 on 2018-08-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_auto_20180821_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='是否已实现'),
        ),
        migrations.AddField(
            model_name='process',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否已删除'),
        ),
        migrations.AlterField(
            model_name='process',
            name='content',
            field=models.CharField(max_length=2000, verbose_name='方法'),
        ),
    ]
