# Generated by Django 2.0.2 on 2018-08-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_auto_20180822_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='count',
            field=models.IntegerField(default=0, verbose_name='倒计时'),
        ),
    ]
