# Generated by Django 2.0.2 on 2018-08-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_plans_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='是否已实现'),
        ),
        migrations.AddField(
            model_name='plans',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否已删除'),
        ),
    ]
